# on cc1110 dev board
CONS_ENABLED=Y
CONS_RX_ENABLED=Y
#ATTR_ENABLED=Y
BUTTONS_ENABLED=Y
LED_P2_3_ENABLED=Y
#SLEEP_ENABLED=Y
#MAC_ENABLED=Y
#ADC_ENABLED=Y
#TX_HIGHPOWER_ENABLED=Y
#PORT1_ISR_ENABLED=Y
CRYSTAL_24_MHZ=Y

