LIBS += apps/$(APP)/json.$(OBJEXT) apps/$(APP)/line.$(OBJEXT)

TX_HIGHPOWER_ENABLED=Y
CONS_ENABLED=Y
CONS_TX_MINIMAL_ENABLED=N
CONS_RX_ENABLED=Y
CONS_RX_MINIMAL_ENABLED=Y
NET_ENABLED=Y
NET_TCP_ENABLED=Y
LED_P2_3_ENABLED=N
COORDINATOR_ENABLED=N
MAC_ENABLED=N
WATCHDOG_ENABLED=Y
SPI_ENABLED=Y
ITOA_ENABLED=Y

CRYPTO_ENABLED=N

